### ISSUE TITLE
what are these files?

### ISSUE THREAD

**Issue by anvesh9652** [Duroktar/Wolf#79]
What the hell are these files? How to delete them? 

![image](https://user-images.githubusercontent.com/83718454/204008059-e7c79614-83ec-4bff-9085-24c8b730d6a9.png)

**Comment by anvesh9652** [comment]
fixed

**Comment by Duroktar** [comment]
Yeah, sorry about those. It was a quick and dirty solution that just worked at the time. I'm assuming you realized you can just delete them without an issue? Wolf makes a new one on each iteration of the code anyways and doesn't need the old ones.

Details aside on the reason it happens.. This "issue" is actually fixed in the [develop](https://github.com/Duroktar/Wolf/tree/develop) branch (that I _really_ need to get around to merging since there's a bunch of other improvements besides this one in there) which if you were so inclined could try out and maybe even help test.
